### ISSUE TITLE
Creating Bearer Auth (JWT) scheme fails governance checks

### ISSUE THREAD

**Issue by neildobson-au** [apigitlabs/apigit-support#19]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

According to https://swagger.io/docs/specification/authentication/bearer-authentication/ the method for defining Bearer Authentication via JWT is to create

```yaml
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
# 2) Apply the security globally to all operations
security:
  - bearerAuth: []         # use the same name as above
```

However, if you view this scheme in the form, the `Scheme` is missing:

![image](https://user-images.githubusercontent.com/6670753/236087349-5c43c87f-38a0-4ae2-8b90-b5c7aa419cb5.png)

This is because `bearer` should be `Bearer` in the UI.

![image](https://user-images.githubusercontent.com/6670753/236087674-e3897dd2-7ef4-49d0-8970-5dd4289ecd40.png)

But if this is left as `Bearer` then it fails governance checks

![image](https://user-images.githubusercontent.com/6670753/236087882-7ae568ab-42aa-4f56-8b19-0bbf796a744d.png)

### Steps To Reproduce

1. Create security scheme as per https://swagger.io/docs/specification/authentication/bearer-authentication/
2. View the scheme in the UI and observe the missing `scheme`
3. Observe that it does pass governance checks
4. Change scheme from `bearer` to `Bearer`
5. Observe it no longer passes governance checks

### Browser

Brave
