### ISSUE TITLE
Inability to store tag descriptions

### ISSUE THREAD

**Issue by neildobson-au** [apigitlabs/apigit-support#21]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

From the tag edit form, when I attempt to edit the descriptions of existing tags, the description values don't persist. In addition, switching between tags seems to carry across the description value from the other tag. But in both cases, the description is dropped when switching to code view.

Existing spec:

```yaml
tags:
  - name: Case
    description: >-
      Create and manage a Case which is a placeholder used to link related
      searches and documents
  - name: Order
    description: Performs provider search which requests and returns documents and data
  - name: Tenant
    description: ''
    externalDocs:
      description: ''
      url: ''
  - name: ClientAccess
    description: ''
    externalDocs:
      description: ''
      url: ''
```

In this example, there's 4 tags and descriptions exist for two of them. If I go to editor and try to edit the description for Tenant or ClientAccess then the value input gets dropped when switching to code view. If I manually input the description values in code view and then switch back to form view then the values appear correctly, but cannot be edited.

### Steps To Reproduce

1. Create a tag
2. Edit description
3. Switch to code view
4. Observe missing description
5. Switch back to form view
6. Description is gone

### Browser

Brave
